### ISSUE TITLE
Overwriting layers produces Issues for Visibility

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/visibility-addin-dotnet#103]
_From @topowright on December 9, 2016 13:55_

Currently the Visibility add-in is configured to overwrite the same four layers for LLOS and the same two layers for RLOS. 

## Expected Behavior
Layers overwrite and tools run properly

## Current Behavior
Layers do not write to TOC
Layers do not write to the default database

## Possible Solution
Have unique names for all layers being written from each tool. 
RLOS - Observers
RLOS - Targets
as an example
## Steps to Reproduce (for bugs)

1.Run the LLOS tool
2.Run the RLOS tool
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

_Copied from original issue: Esri/military-tools-for-arcgis#82_

**Comment by nfeuerstein** [comment]
What do other analytical tools in ArcGIS do?  Do they overwrite the output?  The user is creating this feature for a reason, not because they're interested in what the tool does.  They want to create a feature and persist it, use it somewhere, share it with someone.  Can they do this if the tool automatically overwrites?

**Comment by dhagens** [comment]
@topowright, please update the Expected Behavior for this bug to reflect what we discussed on Friday where the layers will not be overwritten, but new layers will be added after each run.  These layers will be placed in a new group layer after each run of the tool, but the group layers are not currently working properly so the group layer functionality will be added later.

**Comment by topowright** [comment]
This is no longer an issue based on the change that was made where each of the tools writes unique layers each time the tool is run.
