### ISSUE TITLE
LLOS: output graphics missing sight lines (ArcMap)

### ISSUE THREAD

**Issue by elinz** [Esri/visibility-addin-dotnet#119]
When I run a Line of Sight analysis in ArcMap, the resulting graphics are missing sight lines, i.e. no black/white "outer casing" indicating if target is not visible/visible from observer...
![image](https://cloud.githubusercontent.com/assets/4635490/21433539/1053fc2e-c825-11e6-85ba-df760793bad1.png)

Running Line of Sight analysis in ArcGIS Pro creates sight lines...
![image](https://cloud.githubusercontent.com/assets/4635490/21433434/ab7ab0c2-c824-11e6-9145-9a91e198a12c.png)

**Comment by dhagens** [comment]
@topowright @nfeuerstein @kgonzago 

@elinz, When reviewing the code, as the ArcMap addin is currently functioning, the output of the LLOS tool are graphics being displayed on the map, not features.  The sight lines would not be visible if added because they would be hidden by the visible/non-visible observer->target lines.  The output is not being stored anywhere, it is just being displayed on the map.  I don't recall, or know if I was part of the discussion when this tool was originally developed, but does not save output like the Pro addin.  This is a larger issue if the tool should be changed to work like the Pro Addin.  Can someone provide input on this?

**Comment by dhagens** [comment]
We could also generate the sight lines and make them wider than the observer/target lines so that they could be seen underneath.

**Comment by topowright** [comment]
@dhagens I think that is a great idea. I also think that is what we did for ArcGIS Pro.

**Comment by csmoore** [comment]
Added in #177 

![image](https://cloud.githubusercontent.com/assets/3090809/23806862/5dcd191e-0591-11e7-8cec-045be90be610.png)

**Comment by csmoore** [comment]
This is ready to test in next build

**Comment by Dbarnes1** [comment]
@csmoore @elinz verified while at holistic testing for 10.5.1, closing.
