### ISSUE TITLE
RLOS: tool is creating data outside analysis area when set to symbolize non-visible data in output (ArcMap)

### ISSUE THREAD

**Issue by elinz** [Esri/visibility-addin-dotnet#124]
If you check the "Symbolize Non-Visible Data in Output" option, AND set the Field of View so it's not 0 to 360, the output creates non-visible data outside of analysis area.

For example...
![image](https://cloud.githubusercontent.com/assets/4635490/21436830/501e254a-c835-11e6-90be-cd5afce5f559.png)

creates the following output...
![image](https://cloud.githubusercontent.com/assets/4635490/21436875/8173af5c-c835-11e6-8765-a4f385ee7002.png)

The output should not have any data from 180 to 360. This is very misleading to the user as it implies the analysis was performed for 0 to 360.

**Comment by csmoore** [comment]
Looking at this now, we should be able to address this by setting a better feature mask on the raster output.

Since this is also an issue with the minimum/maximum distance was going to address that also with this issue.

However, there is one small workaround required to get the min/max circular arc/slice/swipe to work with this, the observer points must be in the feature mask (or tool fails with "All cells in Raster have the NODATA value.") so the output will look similar to below - with a small visibility output/buffer around the observer points (example highlighted below).

![image](https://cloud.githubusercontent.com/assets/3090809/23903236/32bbdef2-089a-11e7-8327-8340b58f1ed7.png)

**Comment by csmoore** [comment]
Updated in #179 - looks like:

![image](https://cloud.githubusercontent.com/assets/3090809/24377240/b6435224-130c-11e7-9f96-1b5bd8b638e5.png)

Note: I did *not* use the GP Environment Raster Mask approach mentioned above, because it did not seem to work reliably, I added an Intersect GP call to processing (I didn't realize when I started this was how it was already working in ArcMap)

**Comment by csmoore** [comment]
Ready to verify from daily build.

**Comment by Dbarnes1** [comment]
verified, closing
![image](https://cloud.githubusercontent.com/assets/13024357/25507173/5216fd76-2b5f-11e7-8318-c7f768c300d0.png)
