### ISSUE TITLE
LLOS- trying to add image service should get warning in ArcMap 10.5

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/visibility-addin-dotnet#136]
I've been testing visibility and tried to add elevation data to test against from ArcGIS online. I realized that only local elevation data is supported, yet when I add services (mosaic, elevation, image) to the map and open the visibility tool, everything looks like it should work fine. This is a problem because I can run the tool and click OK and get ArcMap to hang up. The functionality needs to be grayed out at minimum, and probably have a warning saying the data isn't supported.

To reproduce:
1. Open ArcMap 10.5
2. Add data, add data from arcgis online and search for "Rhode Island Elevation"
3. You should find an image service called Rhode Island Elevation and Bathymetry, add it to the map.
4. Open the Visibility pane and navigate to the LLOS tab. You'll see that Rhode Island Elevation and Bathymetry is added as the default elevation source. 
5. use the Map Point tool to select target and observer points. 
6. Click OK and watch ArcMap not respond. 

Potential solutions:
Gray out the OK button and put some text in the add-in saying "local elevation data source required" and remove the elevation service from the elevation source drop-down. 

![image](https://cloud.githubusercontent.com/assets/13024357/21734111/901ee174-d416-11e6-9022-903aac38c1d5.png)

**Comment by dhagens** [comment]
@Dbarnes1 @topowright 

I tested this out, and to my surprise, this actually does work.  I'm assuming the issues that you were seeing were because of the distance between Observer and Target points.  If you test with points that are closer in proximity you should see results.  In the bottom screenshot, ArcMap also stopped responding for a few seconds but then came back and I got results.  Not sure there is much we can do about ArcMap not responding when it does eventually come back with results.

![image](https://cloud.githubusercontent.com/assets/13664546/21811218/e5e8fc8a-d71c-11e6-8086-49e6d037f7d4.png)

![image](https://cloud.githubusercontent.com/assets/13664546/21811334/5339a316-d71d-11e6-8985-c46934e41974.png)

**Comment by Thargoids** [comment]
If we did need code to detect whether the dataset is local or via service, I have this.

**Comment by Dbarnes1** [comment]
@dhagens thanks for the tip. I'll try and add some documentation that clarifies the limits to performing llos over a large area. I'm going to try and test both llos and rlos against different types of data sources in both arcmap and pro to see what the limitations are. I verified that the visibility tool worked against this separate dataset over the san francisco bay area (search for san francisco elevation and bathymetry in arcgis online to find it): 

![image](https://cloud.githubusercontent.com/assets/13024357/21819281/e2163c82-d71f-11e6-897f-2476c4b6e952.png)

I'm going to assign this issue back to me and clarify the doc when I figure out exactly what we support.

**Comment by Dbarnes1** [comment]
In arcmap, @NatalieCampos was able to verify that mosaic datasets, image services, and local elevation data work as elevation inputs for the Visibility add-in in ArcMap. As a result, I updated the documentation and I'll close this issue. There are, however, issues using mosaic datasets and image services as inputs in ArcGIS Pro: https://github.com/Esri/visibility-addin-dotnet/issues/147. closing out.
