### ISSUE TITLE
map point tool no longer shows as crosshairs when panning over map in arcmap- both LLOS and RLOS

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/visibility-addin-dotnet#145]
The map point tool still works, but the issue here is that there is no longer the crosshairs that the user would expect. It looks like the normal mouse cursor.

**Comment by dhagens** [comment]
@Dbarnes1, I don't recall that we've ever had crosshairs for LLOS and RLOS tools.  I would suggest that we move this to next iteration since all of our tools work the same way and all would need to be changed.  When using Coordinate Conversion and selecting the MapPoint tool, the cursor is set to the Arrow cursor, the same way it is when using LLOS or RLOS.

**Comment by dhagens** [comment]
@Dbarnes1, I take that back.  Distance & Direction changes to crosshairs.  I will make the change for Visibility.

**Comment by Dbarnes1** [comment]
thanks @dhagens

**Comment by Dbarnes1** [comment]
verified fixed. Thanks @dhagens
