### ISSUE TITLE
Visibility not working with mosaic dataset- Pro 1.4. This causes visibility addin to hang. 

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/visibility-addin-dotnet#147]
@NatalieCampos and I were able to repro this issue where visibility tool (LLOS and RLOS) will throw this error if being run against a mosaic dataset. This works in ArcMap
  
![image](https://cloud.githubusercontent.com/assets/13024357/21869560/0f201ca0-d80d-11e6-86e6-91dfa3fc1c15.png)

Once you close this box, the visibility add-in will hang and render itself unusable. Even if we say for this release that we have a limitation and visibility in pro only accepts local raster data, this hang is cause for high priority status. 

to repro:
1. create a mosaic dataset in a default gdb in a pro project
2. add rasters to this mosaic dataset, you can get these rasters from nsec data. for full path contact myself or @NatalieCampos 
3. run the visibility tool on this mosaic dataset (I ran LLOS), you'll see the tool begin to run, and then the error in the screenshot above.
4. close the error box and attempt to interact with the visibility add-in in pro. This is when we found the add-in to hang.

@nfeuerstein @dhagens fyi.

**Comment by dhagens** [comment]
@NatalieCampos, I tested this out using the MosaicDataset that we use for testing in the MilitaryToolsTestData.gdb and it works fine for me.  I'm wondering if there was an issue with how the MosaicDataset was created or something else at play here.  I will test with my own MosaicDataset and report my findings.
![image](https://cloud.githubusercontent.com/assets/13664546/21892905/ebdfc03e-d8a6-11e6-844e-29f24dbc04cf.png)

**Comment by dhagens** [comment]
@NatalieCampos, I created my own MosaicDataset and added two rasters to it - DTED.  I didn't have any issues running the LLOS tool.  We'll have to go over your workflow to see how the MosaicDataset was created.
![image](https://cloud.githubusercontent.com/assets/13664546/21893565/7592d3aa-d8a9-11e6-9ca7-4bbb09c0e30e.png)

**Comment by Dbarnes1** [comment]
I also can't reproduce this. I changed the documentation to reference that pro supports mosaic datasets. closing.

**Comment by csmoore** [comment]
I believe this is still an issue in some circumstances. I created a simple test mosaic dataset with the source data from: 

https://github.com/Esri/military-tools-geoprocessing-toolbox/tree/dev/testdata/Elevation

And ran the latest version of the addin (which has better error reporting) and got:

![image](https://cloud.githubusercontent.com/assets/3090809/24552695/7b8fbd20-15f5-11e7-96fe-19ea7ff9ab9f.png)

I tried to run this particular GP tool manually with the same layer from the map and it also failed:

![image](https://cloud.githubusercontent.com/assets/3090809/24549884/7225103e-15e9-11e7-8a9c-3eb9e7c9233e.png)

So this may have something to do with the GP tools themselves not handling mosaic map layers correctly, because if I run the tool with the full path to the dataset, it works, so like #181 this may also be an issue with not proving the full path to the dataset to the tool.

![image](https://cloud.githubusercontent.com/assets/3090809/24552884/2e7d6df6-15f6-11e7-9a87-88a759a38a99.png)

**Comment by topowright** [comment]
I have been able to verify that we support a mosaic dataset that is in a spatial reference of PCS, which is not the way that most users store their data.  This can be closed.

**Comment by topowright** [comment]
Verified on ArcGIS Pro 2.0 and Military Tools 2.0. This was tested using our test data with a elevation surface projected to UTM Zone 10
