### ISSUE TITLE
Visibility widget needs to support image services

### ISSUE THREAD

**Issue by csmoore** [Esri/visibility-addin-dotnet#227]
_From @nfeuerstein on May 18, 2017 17:23_

### Widget
Visibility Widget

### Version of widget
1.0

### Bug or Enhancement
Visibility widget needs to support image services.

### Repo Steps or Enhancement details

_Copied from original issue: Esri/solutions-webappbuilder-widgets#878_

**Comment by topowright** [comment]
If the image service end point needs to be a input on the configuration page.

**Comment by adgiles** [comment]
We discussed this at length a while ago, I am still unsure of what is required here. 

The visibility widget relies on an underlying GP Service to function, that is published using ArcGIS Server. This GP service is configured to look at elevation data that is accessible from the ArcGIS Server hosting the GP Service.

From what I remember this requirement came about as a customer did not have their own AGS Server to host the GP service and wanted to be able to just point the widget to an online image service (i think this is supposed to mean an elevation service???), they tried and of course it didn't work (Since then work has been completed within the widget that prevents the user trying to use an invalid service).

This totally changes what this widget was designed for (disconnected users that do not have access to online services). If a user wants to use online services they should consider using the create viewshed analysis (https://doc.arcgis.com/en/arcgis-online/analyze/create-viewshed.htm) and corresponding analysis widget (https://doc.arcgis.com/en/web-appbuilder/create-apps/widget-analysis.htm).

I think feedback on the online viewshed analysis is that it does not provide the same options that our widget does (there are no options for creating a range fan and setting range from and too, it just creates a 360 degree viewshed from the start location out to the range specified). 

A suggestion maybe to push this feedback to the Online team to get them to make the enhancements to the viewshed analysis.

On a side note the Create Viewshed Analysis is a paid for service (uses credits). If we were to create a widget that was capable of producing the same (if not better) results for online customers, would we potentially upset somebody?

**Comment by topowright** [comment]
I agree with @adgiles on this one. I do not think this is a need for the widget at this point. I think this should be closed.

**Comment by topowright** [comment]
@dfoll and @ACueva
