### ISSUE TITLE
Add/Update Build Date when Project built

### ISSUE THREAD

**Issue by csmoore** [Esri/visibility-addin-dotnet#266]
Currently when the project is built, the build date is not updated in the DAML/Addin Info shown to the user.

Similar to how the build automated adding the build number in #217 - It would be helpful to have the build update the Build Date so this is always correct :

Example from an addin built today (2/14/18):
![image](https://user-images.githubusercontent.com/3090809/36228329-eef2c84a-11a1-11e8-81d2-6ec544b51c9f.png)

Here is a working example in this repo of how to update the build date in the DAML in msbuild/VS project (this would need to be integrated with the automated build similar to the build numbers): https://github.com/Esri/visibility-addin-dotnet/commit/fbebd361ffb415285522e812c942377655130407 / https://github.com/Esri/visibility-addin-dotnet/tree/csm/%23266-update-build-date-in-daml

**Comment by topowright** [comment]
Not really sure where to look for a standard, but ArcMap and ArcGIS Pro do not do this, which makes me think that we will understand our release dates and Jenkins has the build date. I am not sure if this is needed: 
![image](https://user-images.githubusercontent.com/5488313/36297079-a27ec05e-12a5-11e8-9348-ef7a6370611e.png)

**Comment by topowright** [comment]
In ArcMap I think our date is tied to the certificate : 
![image](https://user-images.githubusercontent.com/5488313/36297949-4d0f4382-12aa-11e8-9730-e20573066b98.png)

**Comment by csmoore** [comment]
The dates shown on the add-in manager and elsewhere for the addins come from [config.daml](https://github.com/Esri/visibility-addin-dotnet/blob/dev/source/addins/ProAppVisibilityModule/Config.daml#L8) (Pro) and [Config.esriaddinx](https://github.com/Esri/visibility-addin-dotnet/blob/dev/source/addins/ArcMapAddinVisibility/Config.esriaddinx#L9) (ArcMap) - but if there is a compelling reason to continue to set this manually that is OK. We should just remember to update these prior to the next release (perhaps with #267)

**Comment by csmoore** [comment]
@topowright @lfunkhouser - while working on https://github.com/Esri/distance-direction-addin-dotnet/issues/499 - I could also add/update the date - just let me know if this is not desired.

**Comment by topowright** [comment]
@dfoll @ACueva I think there was a conversation that happened with this issue last week while I was out. What was the outcome?

**Comment by lfunkhouser** [comment]
The date should be as close to release as possible and should be updated through the .daml and based off the expected release date per the Solutions Website wiki.

**Comment by csmoore** [comment]
It sounds like the decision is to update the date (in the daml/config/addin files) manually so this issue/idea can be closed.

**Comment by lfunkhouser** [comment]
build number is set in the build script in jenkins. Closing.

**Comment by dannarsavage** [comment]
@lfunkhouser I'm very sorry to tag onto such an old thread, but is there anywhere I can find guidance on how best to set an ArcMap AddIn's version number automatically in Jenkins?  Are there specific msbuild targets in the ArcObjects SDK that can handle this?  I've tried and failed twice to roll my own.

**Comment by csmoore** [comment]
For this project/addin, it is a little tricky, but you should be able to copy/paste from the project files/example shown in this repo:

1. From Jenkins we set these environment variables (ex. %BUILD_MAJOR%) 

2. The project file then sets a variable used by the build: 
https://github.com/Esri/visibility-addin-dotnet/blob/dev/source/addins/ArcMapAddinVisibility/ArcMapAddinVisibility.csproj#L9

3. Finally the prebuilt step edits the daml (XML) file using this variable: 
https://github.com/Esri/visibility-addin-dotnet/blob/dev/source/addins/ArcMapAddinVisibility/ArcMapAddinVisibility.csproj#L256

Hope it helps

Added (just in case you were looking for the Jenkins .bat side of things):

```bat
set BUILD_MAJOR=4
set BUILD_MINOR=0
set BUILD_PATCH=2
call "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\vcvarsall.bat"
call MSBuild "${src_dir}\\Visibility.sln" /t:ArcMapAddinVisibility;ArcMapAddinVisibility_Tests /p:Configuration=Release \|\| exit 1
```

**Comment by dannarsavage** [comment]
Thank so much @csmoore !

**Comment by dannarsavage** [comment]
Okay I'm sorry to be a pest @csmoore , but the steps above get me only as far as I got before (although it gets me there MUCH more elegantly, so thank you again).  I copy/pasted the necessary bits from the csproj file (haven't yet bothered modifying my Jenkins build).  Building that gets me an AddIn that reports version 4.0.0 in ArcMap's AddIn Manager, but the `ThisAddIn.Version` property still tells me I'm at v0.1 (which is what's in Config.esriaddinx before the XmlPoke task is run) when I'm running the built application.  Do you know what it is exactly that rebuilds Config.Designer.cs from Config.esriaddinx and how to kick it off within that `BeforeBuild` target?

**Comment by csmoore** [comment]
OK, it might be my confusion about which addin version you wanted to update (note: that 4.0.0.0 version comes from the .csproj file changes if the BUILD_MAJOR, etc. environment variables aren't set). 

I'm not familiar with "ThisAddIn.Version" - but perhaps that is coming from the `AssemblyInfo.cs` (this is where the dll version itself also come from, ex: https://github.com/Esri/visibility-addin-dotnet/blob/dev/source/addins/ArcMapAddinVisibility/Properties/AssemblyInfo.cs#L35)

**Comment by dannarsavage** [comment]
No, you weren't confused.  The version number that was updated is indeed the version number that I wanted (I ALSO need to update the version of the assembly but that's not your concern).  Here's a play-by-play so hopefully my question is more clear . . .

Line 5 of Config.esriAddinx is `<Version>0.1</Version>`.

Config.Designer.cs contains (among many other things) the class `internal static class ThisAddIn` which has this property `internal static string Version => "0.1";`.  When I manually alter the contents of Config.esriAddinx in Visual Studio so that line 5 says `<Version>I like soup</Version>` and save, VS updates the contents of Config.Designer.cs immediately so that the Version property is now `internal static string Version => "I like soup";`.  (NB: I used expression bodies in this comment just for succinctness but in reality all properties of this class are statement bodies)

Running a build with the target and properties that you pointed me to (thank you again) successfully updates line 5 in Config.esriAddinx, but it fails to precipitate the refresh of Config.Designer.cs before the build proceeds.  My application uses that static property, but I'm not savvy enough to find how to make that refresh happen during a build.  Now that I've typed all this out, I realize this is likely something I should be asking elsewhere.  But since it's here I'll just inflict it upon you so you can tell me off and then I'll copy/paste to stackexchange or something.  :)  Again, thank you very much for your help.

**Comment by dannarsavage** [comment]
FYI... https://gis.stackexchange.com/questions/358850/how-to-trigger-update-to-config-designer-cs-at-build-time
